name: Main CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: npm install
      run: npm install

    # Runs a set of commands using the runners shell
    - name: build
      run: npm run build

    - name:
      env:
        AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_KEY_ID }}'
        AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRET_ACCESS_KEY }}' 
      run: |
        aws s3 cp --recursive --region ap-northeast-2 dist s3://s3-auto-deploy-practice
        && aws s3 cp --recursive --region ap-northeast-2 index.html s3://s3-auto-deploy-practice
